### ISSUE TITLE
Error when trying to ingest dump

### ISSUE THREAD

**Issue by kyle-south** [Saghen/open-library-proxy#11]
When running bun dev this is output I'm getting.  

I'm clueless as to where to look to continue.

>root@readarr-metadata:~/open-library-proxy# bun dev
$ bun --watch run .
Connecting to MongoDB...
Connected to MongoDB
Connecting to MeiliSearch...
Connected to MeiliSearch
Starting ingest...
Ingesting into MongoDB
Clearing...
Processing dump...
106 |      * not subject to semantic versioning compatibility guarantees and may change at any time.
107 |      *
108 |      * @public
109 |      **/
110 |     constructor(message, options) {
111 |         super(message, options);
              ^
error: Invalid BulkOperation, Batch cannot be empty
      at new MongoError (/root/open-library-proxy/node_modules/mongodb/lib/error.js:111:9)
      at new MongoDriverError (/root/open-library-proxy/node_modules/mongodb/lib/error.js:209:9)
      at new MongoAPIError (/root/open-library-proxy/node_modules/mongodb/lib/error.js:238:9)
      at new MongoInvalidArgumentError (/root/open-library-proxy/node_modules/mongodb/lib/error.js:900:9)
      at /root/open-library-proxy/node_modules/mongodb/lib/bulk/common.js:810:19
      at execute (/root/open-library-proxy/node_modules/mongodb/lib/bulk/common.js:787:19)
      at /root/open-library-proxy/node_modules/mongodb/lib/operations/bulk_write.js:29:27
      at execute (/root/open-library-proxy/node_modules/mongodb/lib/operations/bulk_write.js:16:19)
      at /root/open-library-proxy/node_modules/mongodb/lib/operations/insert.js:82:50
      at execute (/root/open-library-proxy/node_modules/mongodb/lib/operations/insert.js:74:19)

**Comment by ZoltrixGFC** [comment]
hey mate, ingest step is failing because you are trying to perform a bulk write with 0 items.
